### ISSUE TITLE
Declarative client workflow support with API interaction with multiple service instances

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/sense-o-py-client#32]
* [ ] 1. Design a slim workflow definition schema similar to FabFed but more compact 
* [ ] 2. Develop client methods for managing "instance group" (similar to FabFed workflow session)
* [ ] 3. Develop new API interaction with SENSE-O to better track and trouble shoot instances in a group. 

Target ETC will be in Dec 2024 to early 2025. The release will be aligned with SENSE-O r25.0.

**Comment by xi-yang** [comment]
Some initial thoughts on the design:
- We consider this workflow as a SENSE service "Client Session" which is like a "Workflow Session" in fabfed. Similarly sessions information will be persisted under a local storage folder. Directory of the folder can be configured in `~/.sense-o-auth.yaml`. 
- A workflow definition template will firstly include `Service Instances` each with reference to a service profile. Primitives such as "count" also apply here. 
- Simple stitching policy can be embedded into the workflow definition. That will be explicit. I don't think we need the policy being inferred from dynamic information or by addition a policy definition configuration file.
- Additional statements for interaction with Manifest, Discovery, AddressManager and MetadataService API will be required. Those will retrieve information from the API as parameters to bind to variables in the Instance profiles.

**Comment by xi-yang** [comment]
@abessiari For initial testing scenarios:
1. Simplest test for N x L2VPN instances. 
   * Use the `Any-to-Any-L2VPN` service profile to create multiple (say `count = 3`) instances in a group. 
   * You can change the terminal URI, vlan tag and bandwidth of the L2VPN. 
   * Exercise create, cancel and repvovision in a group.
   * Exercise modify of count (optional) 
<img width="1178" alt="Screenshot 2024-10-09 at 10 27 29 AM" src="https://github.com/user-attachments/assets/674808a0-d985-4557-97fb-630d1a006394">

2. A L2VPN only stitching scenario:
   * Use the `Any-to-Any-L2VPN-IPv4` profile to create 2x instances. With one stitching to the other. For example, 
      * Instance A: `urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net` VLAN `any` to `urn:ogf:network:es.net:2013::star-cr6:2_1_c5_1:+` VLAN `any`.
      * Instance B: `urn:ogf:network:icair.org:2013:mren8700:esnet` VLAN depending on the produced at `urn:ogf:network:es.net:2013::star-cr6:2_1_c5_1:+` by Instance A, to `urn:ogf:network:starlight.org:2022:r740xd4.it.northwestern.edu` VLAN `any`
   * Before the above two instances, a AddressManager API call to allocate pair of `/30` IPv4 address from the `AutoGOLE-IPv4-Test-Pool` pool and assign that to Instance A terminal `urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net` and Instance B terminal `urn:ogf:network:starlight.org:2022:r740xd4.it.northwestern.edu` respectively. 
   * Exercise create, cancel and repvovision
<img width="1144" alt="Screenshot 2024-10-09 at 10 24 24 AM" src="https://github.com/user-attachments/assets/a3a3cacb-07b4-44b1-b183-30f98cf007a1">
 in a group.

**Comment by abessiari** [comment]
@xi-yang 

So far I support edit entries + manifest. (stitching is next).

Please take under workflow_examples/l2vpn.  This is a combined workflow for fabric and al2s l2vpns.

**Comment by abessiari** [comment]
This is what the  summary looks like:

```
services:
  - !ServiceState
    label: fabric_l2vpn@service
    attributes:
      name: aes_mon_fabric_l2vpn_0
      id: f2f0daa1-b177-4a5c-92d1-7412520dd4d3
      state: CREATE - READY
      profile: FABRIC-L2-Net
      manifest:
        terminals:
          - vlan: '3611'
            port: urn:ogf:network:stack-fabric:2024:topology:node+STAR:port+StarLight-400G-2-STAR:conn+f2f0daa1-b177-4a5c-92d1-7412520dd4d3:vt+l2-policy-Connection_1:vlanport+3611
            name: sense-f2f0daa1-b177-4a5c-92d1-7412520dd4d3
            id: ef3f49aa-4715-4bf1-871e-0ebf49444c81
          - vlan: '3610'
            port: urn:ogf:network:stack-fabric:2024:topology:node+LOSA:port+ResearchNet-400G-LOSA:conn+f2f0daa1-b177-4a5c-92d1-7412520dd4d3:vt+l2-policy-Connection_1:vlanport+3610
            name: sense-f2f0daa1-b177-4a5c-92d1-7412520dd4d3
            id: ef3f49aa-4715-4bf1-871e-0ebf49444c81
  - !ServiceState
    label: al2s_l2vpn@service
    attributes:
      name: aes_mon_al2s_l2vpn_0
      id: 54d559ed-d282-4f55-ba17-761b6293b22e
      state: CREATE - READY
      profile: AL2S-L2VPN
      manifest:
        terminals:
          - vlan: '2405'
            port: urn:ogf:network:al2s.internet2.edu:2023:node+core2.sunn:port+HundredGigE0_0_0_24:conn+54d559ed-d282-4f55-ba17-761b6293b22e:vt+l2-policy-Connection_1:vlanport+2405
            id: 1c908e25-6feb-4889-b0f6-927b51dafb66
          - vlan: '3724'
            port: urn:ogf:network:al2s.internet2.edu:2023:node+core1.star:port+HundredGigE0_0_0_20:conn+54d559ed-d282-4f55-ba17-761b6293b22e:vt+l2-policy-Connection_1:vlanport+3724
            id: 1c908e25-6feb-4889-b0f6-927b51dafb66

```

**Comment by xi-yang** [comment]
The above example is an combination of the two examples under l2vpn folder, correct?

**Comment by abessiari** [comment]
Correct. They are independent but they created under the same session. ....

**Comment by xi-yang** [comment]
> Correct. They are independent but they created under the same session. ....

Can we do X count of instances?

**Comment by abessiari** [comment]
Not just yet. It is a minor change. I wanted to get your feedback on the the we handle the edit/manifest in the configs ....

**Comment by xi-yang** [comment]
@abessiari Some example sense CLI commands for address management.

```
# allocate an IPv4 subnet of mask /64 from the pool named RUCIO_Site_BGP_Subnet_Pool-T2_US_Caltech_Test, default scope
# if batch=2 (a number), that means allocate a number of ip addresses out of a subnet. but the whole subnet will be taken away.
sense_util.py --address allocate,pool=RUCIO_Site_BGP_Subnet_Pool-T2_US_Caltech_Test,type=IPv6,name=unique-alloc-1,batch=subnet,netmask='/64'

# you can free an allocation based on name, or based on address
sense_util.py --address free,pool=RUCIO_Site_BGP_Subnet_Pool-T2_US_Caltech_Test,name=unique-alloc-1
sense_util.py --address free,pool=RUCIO_Site_BGP_Subnet_Pool-T2_US_Caltech_Test,address='2605:d9c0:2:fff1:0:0:0:0/64'

# if the allocation is affiliated with a model resource URI, when that resource is gone, this allocation will be eligible for recycling. In this case, you may not need to free it explicitly 
sense_util.py --address affiliate,pool=RUCIO_Site_BGP_Subnet_Pool-T2_US_Caltech_Test,address=2001:48d0:3001::cb9c,uri=uri:live-resource-uri

```

**Comment by abessiari** [comment]
@xi-yang 

Here is how we are handling dependencies across services. It is generic and very flexible. Service 2 depends
on service1. It gets the value from service1's manifest .... See bold line.

```
config:
  - manifest_template:
      - gcp_manifest_template:
          nodes:
            - name: "?vm_name?"
              image: "?vm_image?"
              sparql: "XXX"
resource:
  - service:
      - serv1:
          manifest_template: '{{ manifest_template.gcp_manifest_template }}'
      - serv2:
          manifest_template: '{{ manifest_template.gcp_manifest_template }}'
          edit_template:
              data.gateways[0].connects[0].authkey: b273e7fe6e35562f5aee21ac87e4e92a
              **data.subnets[0].vms[0].image: '{{ service.serv1.manifest.nodes[0].image }}'**
```

**Comment by abessiari** [comment]
@xi-yang 

I am not able to find to the profiles the Any-To-Any-L2VPN or the Any-To-Any-L2VPN-IPv4.
I have the address service and I would like to try the dependency/assigning ips from
a pool.

**Comment by abessiari** [comment]
@xi-yang 
I amusing the `Any-to-Any-L2VPN-IPv4` and it doest not work even when using the UI.

Please see https://sense-o-dev.es.net:8443/StackV-web/portal/details/dd969687-b9b2-496e-8e26-92d387b11bee?view=logging

The first error is:
pool cannot accomodate requested addresses

**Comment by abessiari** [comment]
@xi-yang 

I could use some help with the manifest query. This is the output I have so far.

```
- !ServiceState
  label: nrp1@service
  attributes:
    name: aes-test-pool_nrp1_0
    id: d503bf3b-c03e-4239-b40a-11c1a848953b
    state: CREATE - READY
    profile: Any-to-Any-L2VPN-IPv4
    manifest:
      terminals:
      - port: urn:ogf:network:nrp-nautilus.io:2020:edgecore_s0:Ethernet40:conn+d503bf3b-c03e-4239-b40a-11c1a848953b:vt+l2-policy-Connection_1:vlanport+3605
        tag: '3605'
      - port: urn:ogf:network:nrp-nautilus.io:2020:edgecore_s0:Ethernet32:conn+d503bf3b-c03e-4239-b40a-11c1a848953b:vt+l2-policy-Connection_1:vlanport+3605
        tag: '3605'
```
